export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_ERROR = 'USER_ERROR'

export const EDIT_PASSWORD_USER_REQUEST = 'EDIT_PASSWORD_USER_REQUEST'
export const EDIT_PASSWORD_USER_SUCCESS = 'EDIT_PASSWORD_USER_SUCCESS'
export const EDIT_PASSWORD_USER_ERROR = 'EDIT_PASSWORD_USER_ERROR'
export const EDIT_PASSWORD_USER_RESET = 'EDIT_PASSWORD_USER_RESET'
